name: build-and-deploy

on:
  push:
    branches:
      - main
      - development

env:
  NODE_ENV: ${{ vars.NODE_ENV }}
  REACT_APP_BACKEND_SERVER: ${{ vars.REACT_APP_BACKEND_SERVER }}

jobs:
  # To build the project for the main branch
  build-main:
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/main'  # Only run for the main branch
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://prod-erp-crm-fe --delete
      
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

  # To build the project for the development branch
  build-development:
    runs-on: ubuntu-latest
    environment: Development
    if: github.ref == 'refs/heads/development'  # Only run for the development branch
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        run: npm install
      - name: Building project
        run: npm run build
      - name: Configure AWS Credentials for Dev
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3 bucket (Dev)
        run: aws s3 sync ./build/ s3://dev-erp-crm-fe --delete
      
      - name: Invalidate Cloudfront (Dev)
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
